### ISSUE TITLE
`__extension__` keyword unsupported

### ISSUE THREAD

**Issue by andrewvaughanj** [ltcmelo/psychec#14]
**If eligible for the bounty, I wish this to be donated to a local animal charity of the maintainer's choice**

#### GCC version:
```bash
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
```

#### clang version:
```bash
clang version 11.0.1
```

#### Output of `gcc -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `clang -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `cnip $FNAME`
```bash
tiny.c:1:14 warning: missing type specifier, assume `int'
# 1 "<stdin>"
              ^
tiny.c:2:14 error: expected , or `;' or = after declarator, got `int'
__extension__ int x;
              ^

(return code 0)
```

#### Content of file
```bash
__extension__ int x;
```

#### `psychec` version
```bash
commit 6d7b8249e0f28af105112b217cb33a24f666e148
Author: Leandro T. C. Melo <LTCMELO@GMAIL.COM>
Date:   Tue Feb 23 07:47:25 2021 -0300

    link expression-parsing table in Doxygen documentation
```

**Comment by ltcmelo** [comment]
Oh… didn't know about `__extension__`, thanks @andrewvaughanj .

**Comment by andrewvaughanj** [comment]
I have no idea if you want this as a separate issue or not ...

#### GCC version:
```bash
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
```

#### clang version:
```bash
clang version 11.0.1
```

#### Output of `gcc -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `clang -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `cnip $FNAME`
```bash
type_of.c:4:4 error: expected expression got `__typeof__'
    __typeof__(x) y = x;
    ^

(return code 0)
```

#### Content of file
```c
int foo(int x)
{
    __typeof__(x) y = x;
    return y;
}
```

#### `psychec` version
```bash
commit 4fea8467c58beb0322ae5b88a5af2d06de851189
Author: Leandro T. C. Melo <LTCMELO@GMAIL.COM>
Date:   Tue Feb 23 17:13:54 2021 -0300

    fix function definitions with pointer declarator in return
```

**Comment by ltcmelo** [comment]
> I have no idea if you want this as a separate issue or not ...

It's OK to leave it here, they'll probably go in the rule of the parser 😉

**Comment by ltcmelo** [comment]
A few cases of `__extension__` were fixed #27  with , but others remain; keeping this open so far. (cc: @andrewvaughanj )

**Comment by ltcmelo** [comment]
Now, with #28 , all cases of `__extension__` @andrewvaughanj  should be fixed (I hope… checked against https://github.com/gcc-mirror/gcc/blob/master/gcc/c/c-parser.c except of open OpenACC).

Keeping open still because of `typeof`.

**Comment by ltcmelo** [comment]
https://github.com/ltcmelo/psychec/commit/c16b6193796eb147e2bb260648e615350798d944 fixes the `__typeof__` case.
