### ISSUE TITLE
`__alignof` keyword unsupported

### ISSUE THREAD

**Issue by andrewvaughanj** [ltcmelo/psychec#17]
**If eligible for the bounty, I wish this to be donated to a local animal charity of the maintainer's choice**

#### GCC version:
```bash
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
```

#### clang version:
```bash
clang version 11.0.1
```

#### Output of `gcc -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `clang -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `cnip $FNAME`
```bash
x86_64-linux-android.c:2:19 error: expected expression got `double'
int a1_i[__alignof(double)];
                   ^

(return code 0)
```

#### Content of file
```bash
int a1_i[__alignof(double)];
```

#### `psychec` version
```bash
commit 6d7b8249e0f28af105112b217cb33a24f666e148
Author: Leandro T. C. Melo <LTCMELO@GMAIL.COM>
Date:   Tue Feb 23 07:47:25 2021 -0300

    link expression-parsing table in Doxygen documentation
```

**Comment by ltcmelo** [comment]
This one should have an immediate fix: add another [alias keyword to alignof](https://github.com/ltcmelo/psychec/blob/4fea8467c58beb0322ae5b88a5af2d06de851189/C/syntax/SyntaxKind.h#L271) in the [group above, with only leading underscores](https://github.com/ltcmelo/psychec/blob/4fea8467c58beb0322ae5b88a5af2d06de851189/C/syntax/SyntaxKind.h#L261-L268). 
Thank you @andrewvaughanj !

**Comment by ltcmelo** [comment]
fixed with https://github.com/ltcmelo/psychec/commit/9af01b9d317b90f3284a34408c5c688d4fe93500
