### ISSUE TITLE
sizeof of expression with bit-field

### ISSUE THREAD

**Issue by GThiago** [ltcmelo/psychec#18]
Hello,

**The snippet**
```c
struct S
{
  signed int i: 32;
};

int main()
{
  int z;
  struct S x = {32};
  z = sizeof(x.i+0);
  return 0;
}
```

Screenshot with gcc, clang, cnip compiled and code:

![Captura de tela de 2021-02-23 12-21-47](https://user-images.githubusercontent.com/52335972/108866202-bc707280-75d2-11eb-9b1e-f4e850a5e5ab.png)

**Comment by GThiago** [comment]
The screenshot of git show --summary.

![Captura de tela de 2021-02-23 12-42-56](https://user-images.githubusercontent.com/52335972/108868173-b4b1cd80-75d4-11eb-8817-a6c5b0c5a95a.png)

**Comment by ltcmelo** [comment]
Thank you @GThiago , you'll get a bounty!

**Comment by alexeyneu** [comment]
so what do you excpect to see there? `32`?

**Comment by GThiago** [comment]
Yup, 32 bit, therefore 4 byte

**Comment by andrewvaughanj** [comment]
I expect the size of to return the size of the expression _after_ doing the addition (including type promotion).

Basically, it totally depends on your architecture and the size of the underlying operands; for example, two `uint32_t`s would give 4; two `uint64_t`s would give 8.

**Comment by ltcmelo** [comment]
Fixed with https://github.com/ltcmelo/psychec/commit/77395bebde146de1d735a6b79ec09696d63fcb13

**Comment by alexeyneu** [comment]
just wanna mention that gcc/msvc  `sizeof` it will not use `( )` overload on that.  it will receive `(expression)` as input.
