### ISSUE TITLE
`__thread` keyword unsupported

### ISSUE THREAD

**Issue by andrewvaughanj** [ltcmelo/psychec#20]
**If eligible for the bounty, I wish this to be donated to a local animal charity of the maintainer's choice**

#### GCC version:
```bash
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
```

#### clang version:
```bash
clang version 11.0.1
```

#### Output of `gcc -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `clang -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `cnip $FNAME`
```bash
darwin-thread-specifier.c:1:14 warning: missing type specifier, assume `int'
# 1 "<stdin>"
              ^
darwin-thread-specifier.c:2:9 error: expected , or `;' or = after declarator, got `int'
__thread int b;
         ^

(return code 0)
```

#### Content of file
```c
__thread int b;
```

#### `psychec` version
```bash
commit 6d7b8249e0f28af105112b217cb33a24f666e148
Author: Leandro T. C. Melo <LTCMELO@GMAIL.COM>
Date:   Tue Feb 23 07:47:25 2021 -0300

    link expression-parsing table in Doxygen documentation
```

**Comment by ltcmelo** [comment]
Cool, thanks once more!

**Comment by ltcmelo** [comment]
Fixed with https://github.com/ltcmelo/psychec/commit/d7616dbd5dc288465aca5a04d31f8669b3689ba8
