### ISSUE TITLE
Declarator may not be initialized (function pointers)

### ISSUE THREAD

**Issue by xavierpinho** [ltcmelo/psychec#21]
**ISO C Standard**
`-std=c11`

**Version**
<img width="460" alt="Screenshot 2021-02-23 at 18 25 54" src="https://user-images.githubusercontent.com/3519109/108889708-9b287a00-7604-11eb-8a5d-01aec3a7a2a8.png">

**The snippet**
```c
int f(int x){return 3;}

int main(){
  int (*z)(int) = f;
}
```

**Comment by ltcmelo** [comment]
Hi @xavierpinho , thank you for the report! Indeed this is a bug, but it's duplicate of #12 , which was reported just a bit ealier than yours; so, I'll mark this one as a duplicate — sorry, but I can't give a bounty for it (perhaps you find another…?)

**Comment by xavierpinho** [comment]
Oh, I completely missed #12! sorry. I'm closing this then.

Best,
