### ISSUE TITLE
Cannot declare variable called `true` or `false`

### ISSUE THREAD

**Issue by andrewvaughanj** [ltcmelo/psychec#29]
#### GCC version:
```bash
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
```

#### clang version:
```bash
clang version 11.0.1
```

#### Output of `gcc -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `clang -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `cnip $FNAME`
```bash
bool.c:0:4 error: expected <identifier> or `(' starting direct-declarator, got `false'
int false;
    ^

(return code 0)
```

#### Content of file
```bash
int false;
```

#### `psychec` version
```bash
commit d10dc1ddfb7ea845f59274a4d6ca5d021ab31423
Author: Leandro T. C. Melo <LTCMELO@GMAIL.COM>
Date:   Tue Mar 9 21:18:30 2021 -0300

    fix postfixing on compound literal
```

**Comment by andrewvaughanj** [comment]
Same for `true`:

#### GCC version:
```bash
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
```

#### clang version:
```bash
clang version 11.0.1
```

#### Output of `gcc -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `clang -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `cnip $FNAME`
```bash
bool.c:0:4 error: expected <identifier> or `(' starting direct-declarator, got `true'
int true;
    ^

(return code 0)
```

#### Content of file
```bash
int true;
```

#### `psychec` version
```bash
commit d10dc1ddfb7ea845f59274a4d6ca5d021ab31423
Author: Leandro T. C. Melo <LTCMELO@GMAIL.COM>
Date:   Tue Mar 9 21:18:30 2021 -0300

    fix postfixing on compound literal
```

**Comment by ltcmelo** [comment]
Thanks @andrewvaughanj , I see that you created a good batch of new issues :wink:.

This behavior is expected: cnip invokes psyche-c's parser with the default language extensions options, which, in turn, consider [true a keyword](https://github.com/ltcmelo/psychec/blob/d10dc1ddfb7ea845f59274a4d6ca5d021ab31423/C/parser/Keywords.cpp#L155-L161) (false as well).

Perhaps I should consider changing this specific default then, to keep consistency with GCC/clang…

**Comment by andrewvaughanj** [comment]
Looking at GCC, if you use `<stdbool.h>` then `true`/`false` get expanded like this:

```
#define bool    _Bool
#define true    1
#define false   0
```

Could `cnip` not true `true`/`false` as built-ins, and get these in the same way via the the `#defines` (you'd need to treat `_Bool` as a built-in).

But I don't know enough as to why `cnip` needs to consider `true` and `false` as "built-ins".

**Comment by ltcmelo** [comment]
>  I don't know enough as to why cnip needs to consider true and false as "built-ins".

It doesn't need to… those just happen to the defaults; I'll adjust those.

However, I can't rely on the `#defines` during **syntax** analysis only, so the content of `<stdbool.h>` will only take effect after **semantic** analysis (which I haven't yet finished int he master branch) — or if the according language extensions are explicitly enabled (after I adjust the defaults).

**Comment by ltcmelo** [comment]
Fixed with https://github.com/ltcmelo/psychec/commit/ca31d32becabd3abf70fc8c82a86f4f57d1b6323
