### ISSUE TITLE
__builtin_va_arg variadic arguments unsupported 

### ISSUE THREAD

**Issue by andrewvaughanj** [ltcmelo/psychec#33]
#### GCC version:
```bash
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
```

#### clang version:
```bash
clang version 11.0.1
```

#### Output of `gcc -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `clang -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `cnip $FNAME`
```bash
varargs.c:0:57 error: expected expression got `long'
long a(__builtin_va_list b) { return __builtin_va_arg(b, long); }
                                                         ^

(return code 0)
```

#### Content of file
```bash
long a(__builtin_va_list b) { return __builtin_va_arg(b, long); }
```

#### `psychec` version
```bash
commit d10dc1ddfb7ea845f59274a4d6ca5d021ab31423
Author: Leandro T. C. Melo <LTCMELO@GMAIL.COM>
Date:   Tue Mar 9 21:18:30 2021 -0300

    fix postfixing on compound literal
```

**Comment by ltcmelo** [comment]
The reason for this error is that `__builtin_va_arg` the `va_arg` macro (builtin) implementation, but Psyche-C is parsing it as a regular function which, in turn, can't accept a type (i.e., `long`) as value argument. 
I'll implementing handling for those builtins.

**Comment by ltcmelo** [comment]
Fixed with https://github.com/ltcmelo/psychec/pull/64.
