### ISSUE TITLE
Help needed to run psychec

### ISSUE THREAD

**Issue by jordiae** [ltcmelo/psychec#48]
Hi, thanks for your contribution. This project is very interesting.

I'm trying to run pyschec and I've found 2 issues:
1. Even after running cmake and make as advised in the README, the psychecgen binary is not generated.
2. Executing the cnip binary doesn't produce any output/file, except when I ask it to dump the AST. For instance, the command: ./cnip --file node.c --C-infer has no effect at all.

What am I doing wrong? Many thanks in advance.

**Comment by andrewvaughanj** [comment]
Is the path to `psychecsolver-exe` (which might be one level above the CMake build folder) on `$PATH`?

**Comment by jordiae** [comment]
> Is the path to `psychecsolver-exe` (which might be one level above the CMake build folder) on `$PATH`?

It is not. But it's not in the directory, either:

```
jordiae@jordiaebook:~/Downloads/psychec$ find . -name "*psychec*"
./C/CMakeFiles/psychecfe.dir
./C/stdlib-support/CMakeFiles/psychecstd.dir
./CMakeFiles/psychecgen.dir
./libpsychecstd.so
./psychecgen
./frontend/CMakeFiles/psychecfe.dir
./frontend/libpsychecfe.so
./solver/psychecsolver.cabal
./stdlib-support/CMakeFiles/psychecstd.dir
./common/CMakeFiles/psychecommon.dir
```

**Comment by andrewvaughanj** [comment]
Hmm, then you should have https://github.com/ltcmelo/psychec/tree/original/solver

**Comment by andrewvaughanj** [comment]
And Stack? You shouldn’t need to install GHC yourself as Stack will install the right version for you.

Try:

```
cd solver
stack build
```

**Comment by jordiae** [comment]
> And Stack? You shouldn’t need to install GHC yourself as Stack will install the right version for you.
> 
> Try:
> 
> ```
> cd solver
> stack build
> ```

I didn't! Gonna try that now, thanks!
