### ISSUE TITLE
Cnip can't handle Duff's device —  K&R style function declarations

### ISSUE THREAD

**Issue by gahag** [ltcmelo/psychec#6]
Tested with GCC and Clang with options: `-c -std=c11 -pedantic test.c`, no warnings or errors reported.

**ISO C Standard**
`-std=c11`

**Version**
Tag, branch, commit, or screenshot of `git show --summary`: 66415a2f6a1c1359a3777cc29ad0f776ecb8c959
![image](https://user-images.githubusercontent.com/7347561/108637454-895e9f80-7469-11eb-8e2c-647f53f88f2d.png)

Cnip outputs quite a few more errors, which were not included in the screenshot.

**The snippet**
The infamous [Duff's device](https://en.wikipedia.org/wiki/Duff%27s_device)
```c
void send(to, from, count)
register short *to, *from;
register int count;
{
    register int n = (count + 7) / 8;
    switch (count % 8) {
    case 0: do { *to = *from++;
    case 7:      *to = *from++;
    case 6:      *to = *from++;
    case 5:      *to = *from++;
    case 4:      *to = *from++;
    case 3:      *to = *from++;
    case 2:      *to = *from++;
    case 1:      *to = *from++;
            } while (--n > 0);
    }
}
```
In particular, it seems like there are two bugs here:
1. Cnip can't handle K&R style function declarations.
2. Cnip can't handle intertwined `switch` and `do while` statements.

Hope this can be of help :)

**Comment by ltcmelo** [comment]
Thank you @gahag . Yes, it's of great help, you'll get a bounty!

**Comment by condekind** [comment]
That was the first thing I thought of after I saw the bounty program! Didn't have time earlier, too bad I'm late for the candy.
To be fair I didn't think gcc/clang themselves would stay silent with -std=c11 and -pedantic. Nice find! :)

**Comment by ltcmelo** [comment]
Fixed in https://github.com/ltcmelo/psychec/pull/84.
