### ISSUE TITLE
Valid compound literal not recognized

### ISSUE THREAD

**Issue by condekind** [ltcmelo/psychec#7]
Compiled without errors with GCC and Clang (both trunk) with options -c and -pedantic

**ISO C Standard**
`-std=c11`

**Version**
Screenshot of `git show --summary` plus a local compilation (also tested in Godbolt's Comp. Explorer):

![commit](https://lh3.googleusercontent.com/pw/ACtC-3flEQ8CAzp64hd-dP1vhm9mmJ88CJkG0WmDWqJ0MYu91FVu_elOEd9yrh8ZwX0-zYoVyUl-SJ7HpXxvPRcSRRHJtepcI2JkihauMlKo_VUK_XTKZ-XujkHFKWW3G1ztfIkszMxnkoiBZ5FGpN6sx4iW8w=w1024-h585-no)

**The snippet**
```c
int main() {

  struct s_s
  {
    int i;
  };

  return (struct s_s){.i=42}.i;
}
```

Hope it helps, psyche-c helped us a lot when working on AnghaBench :)

**Comment by ltcmelo** [comment]
Thank you @condekind , sure it helps (you'll get a bounty). And I'm glad to hear that psyche was of aid.

**Comment by ltcmelo** [comment]
Fixed with https://github.com/ltcmelo/psychec/commit/d10dc1ddfb7ea845f59274a4d6ca5d021ab31423
