### ISSUE TITLE
Cannot parse functions that return pointers

### ISSUE THREAD

**Issue by malbarbo** [ltcmelo/psychec#8]
Compiled without errors with GCC and Clang with options `-c -std=c11 -pedantic`.

**ISO C Standard**
`-std=c11`

**Version**

```
commit cb578e9d10c2cc67980e9f383f9afd542f784e17 (HEAD -> master, origin/master, origin/HEAD)
Author: Leandro T. C. Melo <ltcmelo@gmail.com>
Date:   Mon Feb 22 10:24:11 2021 -0300

    add Psyche-C logo
```

**The snippet**

```c
int *f() {
  return 0;
}
```

**Comment by ltcmelo** [comment]
Thank you for the report @malbarbo , the parser is (incorrectly) making an object pointer declarator in this case. You'll get a bounty!

**Comment by ltcmelo** [comment]
Fixed with https://github.com/ltcmelo/psychec/commit/4fea8467c58beb0322ae5b88a5af2d06de851189
